	public void update(User value) throws AppException
	{
		if (Update.table("Uzer")
			.set("active", value.getActive())
			.set("username", value.getUsername())
			.set("password", value.getPassword())
			.set("name", value.getName())
			.set("email", value.getEmail())
			.set("Role$id", value.getRole().getId())
			.set("description", value.getDescription())
			.set("cellPhone", value.getCellPhone())
			.set("phone", value.getPhone())
			.set("photo", value.getPhoto())
			.set("birthdate", value.getBirthdate())
			.set("CPF", value.getCPF())
			.set("sex", value.getSex())
			.set("registration", value.getRegistration())
			.set("code", value.getCode())
			.where(Condition.of("id").eq(value.getId()))
			.build()
			.connect(getLink())
			.execute() == 0)
			throw new NotFoundException();
	}